<?php

namespace GamingSchoolBundle\Repository;

/**
 * BoostingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoostingRepository extends \Doctrine\ORM\EntityRepository
{
}
