<?php

namespace GamingSchoolBundle\Repository;

/**
 * CoachingPackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoachingPackRepository extends \Doctrine\ORM\EntityRepository
{
}
