<?php

namespace GamingSchoolBundle\Repository;

/**
 * CoachingLessonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoachingLessonRepository extends \Doctrine\ORM\EntityRepository
{
}
