<?php

namespace GamingSchoolBundle\Repository;

/**
 * CoachingSoldRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoachingSoldRepository extends \Doctrine\ORM\EntityRepository
{
}
