<?php

namespace GamingSchoolBundle\Repository;

/**
 * CoachingPackRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoachingPackRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCoachingPackByCoach($coach)
    {
        $qb = $this->createQueryBuilder('u');
        $qb->where('cp.coachingPackCoachId = :coach')
            ->setParameter('coach', $coach);

        return $qb->getQuery()->getResult();
    }
}
