<?php

namespace GamingSchoolBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByCoaches($game)
    {
        $qb = $this->createQueryBuilder('u');
        $qb->distinct()
        	->leftJoin('GamingSchoolBundle:CoachingPack', 'cp', 'WITH', 'cp.coachingPackCoachId = u.id')
        	->where('cp.coachingPackGameId = :game')
        	->setParameter('game', $game);
        return $qb->getQuery()->getResult();
    }
}
